services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Patinhado:/app/Patinhado
    env_file:
      - ./Patinhado/.env
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
