# Generated by Django 6.0.4 on 2026-06-26 18:53

import backend.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pet_foto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', backend.models.UsuarioManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='pedidoadocao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', help_text='Status do pedido: pendente, aprovado, rejeitado, cancelado', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], default='cachorro', help_text='Espécie do animal: cachorro, gato ou outro', max_length=20),
        ),
    ]
